resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: gpdb_pr
    type: pull-request
    source:
      repository: greenplum-db/gpdb
      access_token: ((gpdb-git-access-token))
      base_branch: "5X_STABLE"
      ignore_paths:
        - gpdb-doc/*
        - README*

  - name: centos-gpdb-dev-6
    type: docker-image
    source:
      repository: pivotaldata/centos-gpdb-dev
      tag: '6-gcc6.2-llvm3.7'

  - name: binary_swap_gpdb_centos6
    type: s3
    source:
      access_key_id: {{bucket-access-key-id}}
      bucket: {{bucket-name}}
      region_name: {{aws-region}}
      secret_access_key: {{bucket-secret-access-key}}
      versioned_file: {{binary_swap_gpdb_centos_versioned_file}}

  - name: bin_gpdb_centos6
    type: s3
    source:
      access_key_id: {{bucket-access-key-id}}
      bucket: {{bucket-name}}
      region_name: {{aws-region}}
      secret_access_key: {{bucket-secret-access-key}}
      versioned_file: {{bin_gpdb_centos_versioned_file}}

jobs:
  - name: compile-and-test-pull-request
    plan:
      - aggregate:
          - get: gpdb_pr
            version: every
            trigger: true
          - get: bin_gpdb
            resource: bin_gpdb_centos6
            trigger: true
          - get: binary_swap_gpdb
            resource: binary_swap_gpdb_centos6
            trigger: true
          - get: centos-gpdb-dev-6
            trigger: true

      - aggregate:
        - put: gpdb_pr
          params:
            path: gpdb_pr
            status: pending
        - task: ic_gpdb
          file: gpdb_pr/concourse/tasks/ic_gpdb_binary_swap.yml
          image: centos-gpdb-dev-6
          input_mapping:
            gpdb_src: gpdb_pr
          params:
            MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=off' installcheck-world
            BLDWRAP_POSTGRES_CONF_ADDONS: "fsync=off"
            TEST_OS: centos
            CONFIGURE_FLAGS: {{configure_flags}}

      - put: report_pr_success
        resource: gpdb_pr
        params:
          path: gpdb_pr
          status: success
