platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: bin_gpdb
outputs:
  - name: rc_bin_gpdb
run:
  path: gpdb_src/concourse/scripts/remove_non_production_files.sh
params:
  NON_PRODUCTION_FILES: gpdb_src/gpAux/releng/NON_PRODUCTION_FILES.txt
  INPUT_TARBALL: bin_gpdb/bin_gpdb.tar.gz
  OUTPUT_TARBALL: rc_bin_gpdb/bin_gpdb.tar.gz
