platform: linux
inputs:
 - name: gpdb_src
 - name: ccp_src
 - name: cluster_env_files
outputs:
 - name: coverage
run:
  path: bash
  args:
  - -c
  - |
    set -ex

    ccp_src/scripts/setup_ssh_to_cluster.sh

    # TODO: ask CCP maintainers for a feature to do this for us
    scp cluster_env_files/hostfile_all mdw:/tmp

    # Install patchelf. We need to SSH as root, hence the use of
    # cluster_env_files.
    ssh -t ccp-$(cat cluster_env_files/terraform/name)-0 "sudo bash -c '
        source /home/gpadmin/gpdb_src/concourse/scripts/common.bash
        install_python_hacks
    '"

    ssh -t mdw "
        source /home/gpadmin/gpdb_src/concourse/scripts/common.bash
        install_python_requirements_on_multi_host /home/gpadmin/gpdb_src/gpMgmt/requirements-dev.txt

        # Enable coverage.py on all hosts. (This modifies greenplum_path.sh and must
        # come before the source below.)
        setup_coverage /home/gpadmin/gpdb_src

        $CUSTOM_ENV bash /home/gpadmin/gpdb_src/concourse/scripts/run_behave_test.sh \"$BEHAVE_FLAGS\"
    "

    # collect coverage
    while read -r host; do
        scp -r "$host:/tmp/coverage/*" ./coverage/
    done < cluster_env_files/hostfile_all

    source ./gpdb_src/concourse/scripts/common.bash
    tar_coverage "${TEST_NAME}_ccp"
