platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/qp-gpdbdev
inputs:
  - name: gporca-commits-to-test
  - name: bin_orca
  - name: bin_xerces
  - name: bin_gpdb
  - name: gpdb_main_src
  - name: gpdb_tarball
outputs:
  - name: icg_output
run:
  path: gpdb_main_src/concourse/scripts/untar_and_build_gpdb.py
params:
  MODE: orca
  ACTION: test
  BLDWRAP_POSTGRES_CONF_ADDONS: statement_mem=250MB
  CONFIGURE_OPTION: --disable-gpcloud
