resources:
  - name: gpdb_src
    type: git
    source:
      uri: https://github.com/greenplum-db/gpdb.git
      branch: master

  - name: docker-image
    type: docker-image
    source:
      repository: pivotaldata/greenplum-server-ubuntu-18
      tag: latest

      
anchors:
  - &fetch_source
    get: gpdb_src
    trigger: true
    version: every

  - &fetch_image
    get: image
    resource: docker-image


tasks:
  - &task
    image: image
    file: gpdb_src/concourse/server_pipeline/task.yml
    timeout: 3h
    
  - &test_installcheck_world_with_planner
    <<: *task
    task: test_installcheck_world_with_planner
    params:
      PGOPTIONS: '-c optimizer=off'
      MAKE_TASK: installcheck-world

  - &test_installcheck_world_with_orca
    <<: *task
    task: test_installcheck_world_with_orca
    params:
      PGOPTIONS: '-c optimizer=on'
      MAKE_TASK: installcheck-world
      

jobs:
  - name: compile_and_test_gpdb
    public: true
    max_in_flight: 10
    plan:
    - aggregate:
      - *fetch_source
      - *fetch_image

    - aggregate:
      - *test_installcheck_world_with_orca
      - *test_installcheck_world_with_planner
